/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author HP
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
         Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNs = new javax.swing.JButton();
        btnNb = new javax.swing.JButton();
        btnRb = new javax.swing.JButton();
        btnIb = new javax.swing.JButton();
        btnSs = new javax.swing.JButton();
        btnLo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNs.setText("New Student");
        btnNs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNsActionPerformed(evt);
            }
        });
        getContentPane().add(btnNs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 50));

        btnNb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNb.setText("New Book");
        btnNb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNbActionPerformed(evt);
            }
        });
        getContentPane().add(btnNb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 190, 50));

        btnRb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRb.setText("Return Book");
        btnRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRbActionPerformed(evt);
            }
        });
        getContentPane().add(btnRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 190, 50));

        btnIb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnIb.setText("Issue Book");
        btnIb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIbActionPerformed(evt);
            }
        });
        getContentPane().add(btnIb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 50));

        btnSs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSs.setText("Statistics");
        btnSs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSs, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 160, 50));

        btnLo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLo.setText("Logout");
        btnLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoActionPerformed(evt);
            }
        });
        getContentPane().add(btnLo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home final.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSsActionPerformed
        // TODO add your handling code here:
        new IssueDetails().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSsActionPerformed

    private void btnIbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIbActionPerformed
        // TODO add your handling code here:
        new Issuebook().setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_btnIbActionPerformed

    private void btnRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRbActionPerformed
        // TODO add your handling code here:
        new Returnbook().setVisible(true);
        this.setVisible(false);
      
    }//GEN-LAST:event_btnRbActionPerformed

    private void btnNbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNbActionPerformed
        // TODO add your handling code here:
        new newbook().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNbActionPerformed

    private void btnNsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNsActionPerformed
        // TODO add your handling code here:
        
      new new_student().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btnNsActionPerformed

    private void btnLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoActionPerformed
        // TODO add your handling code here:
         new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIb;
    private javax.swing.JButton btnLo;
    private javax.swing.JButton btnNb;
    private javax.swing.JButton btnNs;
    private javax.swing.JButton btnRb;
    private javax.swing.JButton btnSs;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private static class returnbook {

        public returnbook() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
